[package]
name = "paddle_notifications_logger"
version = "0.1.0"
edition = "2021"

[lib]
name = "myhtmxlib"
path = "src/lib.rs"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_client = { path = "../../lib/aws_client" }
axum_helper = { path = "../../lib/axum_helper" }
anyhow = { version = "1.0.75", features = ["backtrace"] }
axum = "0.6.20"
http = "0.2.9"
lambda_runtime = "0.8.2"
openssl = { version = "0.10.57", features = ["vendored"] }
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
tokio = { version = "1", features = ["full", "tracing"] }
tower = "0.4.13"
tower-http = {version = "0.4.4", features = ["full","sensitive-headers"]} # ["normalize-path","trace"]}
tracing = "0.1.37"
tracing-subscriber = {version="0.3.17", features=["env-filter"]}
hyper = "0.14.27"
http-body = "0.4.5"

[dependencies.lambda_http]
version = "0.8.1"
default-features = false
features = ["apigw_rest"]
